### ISSUE TITLE
DynamoDB feature store support

### ISSUE THREAD

**Issue by Vlaaaaaaad** [launchdarkly/python-client#102]
For serverless usecases [DynamoDB was implemented as a feature store state in the Go, Java, .NET and Node SDKs](
https://docs.launchdarkly.com/v2.0/docs/using-a-persistent-feature-store#section-using-dynamodb).

Creating this issue to express interest in supporting DynamoDB feature store in the Python SDK too.

**Comment by eli-darkly** [comment]
Hi! Same answer as to your Ruby comment - Python support will be in the next release.

**Comment by eli-darkly** [comment]
Just released version 6.7.0 of the Python SDK, which includes a DynamoDB integration. The reference guide page you linked to has been updated with an example. If you try it out, please let us know whether it meets your needs.
