### ISSUE TITLE
Can jsonpickle's version restriction be relaxed? (0.9.3 -> 0.9.6)

### ISSUE THREAD

**Issue by phobologic** [launchdarkly/python-client#109]
Hi, I'm trying to make use of launchdarkly in my app, but I'm having issues because of the fact that we also use jsonpickle in it, and we're using it at version 0.9.6.  I was wondering if there was anything stopping this library from updating to <1.0.0?  1.0 they got rid of python 3.3 support (since it EOLd), so I understand if you can't upgrade there, but 0.9.6 should be version safe/compatible, and even adds some new features/clears up some old bugs.

Thanks!

**Comment by eli-darkly** [comment]
I'm not sure we actually need jsonpickle at all in this code, as we're only serializing built-in types like dict. We made an effort a little while ago to remove dependencies that weren't really serving any purpose, but that's one we may have missed. I'll double-check, but I think it's safe to say we can either remove it or  just change the version constraint as you suggest.

**Comment by eli-darkly** [comment]
As of the 6.8.3 release, the SDK no longer uses jsonpickle. Thanks for pointing this out.
