### ISSUE TITLE
RedisFeatureStore should handle redis outage

### ISSUE THREAD

**Issue by pdsarin** [launchdarkly/python-client#67]
From my reading of the code and from some limited testing, the LaunchDarkly client gracefully handles unavailability of the LaunchDarkly service.

The RedisFeatureStore does not appear to handle outages gracefully. IMO it should return the default when redis is unavailable. (I discovered the problem when I had my redis URL misconfigured while running in ldd mode.)

**Comment by drichelson** [comment]
Thanks for bringing this to our attention. We'll be investigating soon.

**Comment by drichelson** [comment]
@pdsarin We've just released 4.0.1 which addresses this issue. Please let us know if it works for you.

**Comment by pdsarin** [comment]
Works great. Thank you!
