### ISSUE TITLE
Install broken on pip 10.x

### ISSUE THREAD

**Issue by mattbriancon** [launchdarkly/python-client#80]
From the [pip CHANGELOG](https://pip.pypa.io/en/stable/news/#b1-2018-03-31):

> Move all of pip's APIs into the pip._internal package, properly reflecting the fact that pip does not currently have any public APIs. (#4696, #4700)

```
Collecting ldclient-py==4.0.6 (from -r requirements.txt (line 74))
  Downloading ldclient-py-4.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qsq8HS/ldclient-py/setup.py", line 9, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qsq8HS/ldclient-py/
```

**Comment by urgas9** [comment]
Struggling with the same issue here, would need this fixed.

**Comment by theholy7** [comment]
Same here. Please fix :)

**Comment by ramkrk** [comment]
Same issue. Needs work for PIP 10.
I think it should be 
`from pip._internal.req import parse_requirements `

`Downloading ldclient-py-4.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e0Js8h/ldclient-py/setup.py", line 9, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-e0Js8h/ldclient-py/
`

**Comment by p4bloch** [comment]
Any workarounds in the meantime? Downgrading pip?

**Comment by eli-darkly** [comment]
Sorry about this. We'll be putting out a patch release to fix it today— probably will go with implementing the function ourselves as @theholy7 suggested, rather than importing the non-public API which could just get us in trouble again in the future.

(Also in the meantime, downgrading pip is the only workaround as far as I know.)

**Comment by theholy7** [comment]
@eli-darkly - Just submitted a PR - hopefully it follows your standards :)

**Comment by eli-darkly** [comment]
`ldclient-py` 5.0.4 has been released with this fix. Thanks to everyone who reported this and/or submitted PRs.
