### ISSUE TITLE
Inaccurate uwsgi `enable-threads` error logging

### ISSUE THREAD

**Issue by dougkeen** [launchdarkly/python-client#84]
Right now, if you run the client in a uwsgi environment without the `enable-threads` option set, this message gets error logged:
> The LaunchDarkly client requires the enable-threads option be passed to uWSGI.

However, the uwsgi config could _not_ have `enable-threads` explicitly set, but rather have threads [implicitly enabled by setting a `threads` option](http://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html).
> By default the Python plugin does not initialize the GIL. This means your app-generated threads will not run. If you need threads, remember to enable them with enable-threads. Running uWSGI in multithreading mode (with the threads options) will automatically enable threading support. This “strange” default behaviour is for performance reasons, no shame in that.

In the case where `enable-threads` is not specified in the uwsgi config, but `threads` is, the LaunchDarkly client will incorrectly log the above error message.

**Comment by eli-darkly** [comment]
Thanks. This seems like a straightforward change. I'm currently working on setting up a test environment for it, so we can make sure we're reading the options correctly.

**Comment by eli-darkly** [comment]
Fixed in version 6.0.2.
