### ISSUE TITLE
Add Support for Python 3.7

### ISSUE THREAD

**Issue by levlaz** [launchdarkly/python-client#92]
[Python 3.7](https://www.python.org/downloads/release/python-370/) was released yesterday. As folks start moving over to this version it would be nice to stay ahead of things and add proper support.

**Comment by eli-darkly** [comment]
We've added the prerelease `3.7-rc` version to our CI builds and it seems to work fine. There isn't a Docker image available yet for the released `3.7`, but as soon as there is, we'll start using that.

**Comment by eli-darkly** [comment]
The CI tests are now running with the official 3.7 release, and I've also manually tested with 3.7 from the command line. Looks good.
